### ISSUE TITLE
run_<model>_<dataset>.sh does not work

### ISSUE THREAD

**Issue by thomasgirault** [mnick/holographic-embeddings#4]
Hello,
I tried to execute the scripts but it gives me this error :

```INFO:EX-KG:Fitting model HolE with trainer PairwiseStochasticTrainer and parameters Namespace(afs='sigmoid', fin='data/wn18.bin', fout=None, init='nunif', lr=0.1, margin=0.2, me=500, mode='rank', nb=100, ncomp=150, ne=1, no_pairwise=False, rparam=0, sampler='random-mode', test_all=50)
Traceback (most recent call last):
  File "kg/run_hole.py", line 61, in <module>
    ExpHolE().run()
  File "/home/thomas/dev/KGE/holographic-embeddings/kg/base.py", line 50, in run
    self.train()
  File "/home/thomas/dev/KGE/holographic-embeddings/kg/base.py", line 154, in train
    trn.fit(xs, ys)
  File "/home/thomas/bin/miniconda/lib/python3.6/site-packages/scikit_kge-0.1-py3.6.egg/skge/base.py", line 197, in fit
    scores_o = self.scores_o(mdl, s, p).flatten()
  File "/home/thomas/bin/miniconda/lib/python3.6/site-packages/scikit_kge-0.1-py3.6.egg/skge/base.py", line 142, in _optim
    sampler = sample.RandomModeSampler(self.args.ne, [0, 1], xs, sz)
  File "/home/thomas/bin/miniconda/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 509, in split
    res = array_split(ary, indices_or_sections, axis)
  File "/home/thomas/bin/miniconda/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 430, in array_split
    sub_arys.append(_nx.swapaxes(sary[st:end], axis, 0))
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by Lily1756** [comment]
I get a similar problem. So, did you fix it?
```
Traceback (most recent call last):
  File "kg/run_hole.py", line 64, in <module>
    ExpHolE().run()
  File "/data/zhangyi/micbio/codes/model/HOLE/holographic-embeddings/kg/base.py", line 50, in run
    self.train()
  File "/data/zhangyi/micbio/codes/model/HOLE/holographic-embeddings/kg/base.py", line 139, in train
    cards = cardinalities(xs,ys,sz)
  File "/data/zhangyi/micbio/codes/model/HOLE/holographic-embeddings/kg/base.py", line 350, in cardinalities
    T = to_tensor(xs, ys, sz)
  File "build/bdist.linux-x86_64/egg/skge/util.py", line 76, in to_tensor
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
